### PR TITLE
Update zh_cn.json 1.15

### PR DESCRIPTION
**Pull request by Aemande123**
Update zh_cn.json 1.15

In addition
Can I move your mods(The-Midnight) to mcbbs?
mcbbs:https://www.mcbbs.net/
mcbbs is the largest minecraft fan forum in China
I will continue to follow up with localization files.

I will not provide download sources other than Curseforge

I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge,also unable to log in Discord and Twitter.

### CODE REVIEW

**Comment by Aemande123** [comment]
> Update zh_cn.json 1.15
> 
> In addition
> Can I move your mods(The-Midnight) to mcbbs?
> mcbbs:https://www.mcbbs.net/
> mcbbs is the largest minecraft fan forum in China
> I will continue to follow up with localization files.
> 
> I will not provide download sources other than Curseforge
> 
> I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge,also unable to log in Discord and Twitter.

**Comment by EnterFor** [comment]
大佬辛苦了

**Comment by Jonathing** [comment]
If you are to reference The Midnight anywhere, *you must link back to the CurseForge page or download.* In addition, we have a new website for translations of this mod.

https://mcmodtranslations.oneskyapp.com/collaboration/project?id=349913

Please do the rest of your translation work there, if you can.

**Comment by Aemande123** [comment]
> If you are to reference The Midnight anywhere, _you must link back to the CurseForge page or download._ In addition, we have a new website for translations of this mod.
> 
> https://mcmodtranslations.oneskyapp.com/collaboration/project?id=349913
> 
> Please do the rest of your translation work there, if you can.

All right

**Pull request merged**
